apiVersion: v1
kind: Namespace
metadata:
  name: auth-staging
  labels:
    app.kubernetes.io/part-of: qooma
    env: staging
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: auth-staging-quota
  namespace: auth-staging
spec:
  hard:
    requests.cpu: '1500m'
    requests.memory: '2Gi'
    limits.cpu: '3000m'
    limits.memory: '4Gi'
    persistentvolumeclaims: '5'
    pods: '10'
